"""Fix Workout model

Revision ID: 2498bbdd1f01
Revises: 2576511845e8
Create Date: 2025-03-13 00:51:17.174811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2498bbdd1f01'
down_revision: Union[str, None] = '2576511845e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('workouts', 'exercise')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('exercise', sa.VARCHAR(), nullable=False))
    op.drop_column('workouts', 'title')
    # ### end Alembic commands ###
